### PR TITLE
Add chunk complete notification

### PR DESCRIPTION
**Pull request by gingermusketeer**

### CODE REVIEW

**Comment by gingermusketeer** [comment]
This allows the consumer of the library to display the actual amount of data that has been received by the server.

Using the existing on progress event means that the progress bar jumps around when a chunk of the upload fails

**Comment by gingermusketeer** [comment]
Looks like the build is failing due the sauce labs credentials not being present. 

Comparing the above build to the last [successful build](https://travis-ci.org/tus/tus/tus-js-client/builds/84582245) I noticed the following is missing

```bash
#Setting environment variables from repository settings
$ export SAUCE_USERNAME=[secure]
$ export SAUCE_ACCESS_KEY=[secure]
```

**Comment by Acconut** [comment]
This looks good, I will give it a deep review the next days. Regarding the failing Travis CI build: For Pull Requests the secure environment variables are left out, to ensure they are not leaked to untrusted code. Else someone can open a PR and add `echo $SAUCHE_ACCESS_KEY` to .travis.yml and see it key in clear text. :)

**Comment by gingermusketeer** [comment]
@Acconut No problem. Let me know if there is anything you want changed.

I have created a PR which runs the tests on Phantom for PR branches. See #13 

Hopefully this is helpful

**Comment by Acconut** [comment]
I added some more documentation about the new functionality.
Thank you a lot for both of your PRs. :+1:  <3

**Comment by gingermusketeer** [comment]
No problem. Glad to help

**Pull request merged**
