### PR TITLE
Fix for issue #652: retryDelays type missing null

### PR DESCRIPTION
**Pull request by dmitryprusakov**
Issue: https://github.com/tus/tus-js-client/issues/652

### CODE REVIEW

**Review by Acconut — APPROVED** [review]
Thank you very much!

**Comment by dmitryprusakov** [comment]
@Acconut , also approximately when will this be released?

**Comment by Acconut** [comment]
It has already been released in v3.1.2

**Comment by dmitryprusakov** [comment]
@Acconut, thats great, thanks!
Maybe you also know when it will be updated as dependency in @uppy/tus?
Or I need to ask in uppy repo about this?

**Comment by Acconut** [comment]
Please ask this question in the Uppy repository or in the community forum at https://community.transloadit.com/

**Pull request merged**
