### PR TITLE
create .babelrc

### PR DESCRIPTION
**Pull request by taoqf**

### CODE REVIEW

**Comment by kvz** [comment]
Hi, what is the advantage of this approach over having it in the package.json?

**Comment by arturi** [comment]
Yeah, we are getting this in React Native build:

img_5330

And the solution would likely be to 1. move the config to `.babelrc` like @taoqf did here; and 2. add it to [`.npmignore`](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) so build tools are not confused with babel configs they shouldn’t care for.

Are you ok with this @Acconut? Or maybe we should use [`files`](https://docs.npmjs.com/files/package.json#files).

**Comment by Acconut** [comment]
Frankly, I am unsure how the Babel configuration is connected to React Native but if that fixes it, I am open for this and following PRs.

**Comment by arturi** [comment]
React Native uses a build setup, which looks into babel configs for all dependencies in `node_modules`.

Renee:
> react native runs babel on deps i guess

**Comment by taoqf** [comment]
I am not using react , just webpack, also come into this issue. @arturi

**Comment by Acconut** [comment]
Ok, I went ahead and merged this. Let me know if anything else is needed for Webpack or React Native.

**Comment by kvz** [comment]
I think what we need next is add `.babelrc` to `.npmignore` (blacklist) OR: add all files we want present in the npm module to `files` in the `package.json` (whitelist).

Personally, I'm a fan of the whitelist approach, for the simple reason that it's harder to accidentally add things to the npm registry (like secrets, or what have you). It's hard to undo a publish, and unlike git, you don't really get to explicitly commit which things go into a module (unless you use `files`! :)

**Comment by Acconut** [comment]
In https://github.com/tus/tus-js-client/pull/119 @arturi added the `files` property to `package.json`.

Further work for fully supporting React Native is discussed in #96

**Pull request merged**
