### PR TITLE
Remove fingerprint from storage on success.

### PR DESCRIPTION
**Pull request by mperrando**
See #97.

### CODE REVIEW

**Comment by Acconut** [comment]
Thank you very much, this is looking very good. However, since this is a breaking change, I would recommend to move this behaviour behind an option flags is enabled (maybe call it `clearFingerprintAfterSuccess`?)

**Comment by mperrando** [comment]
Ok, no problema about that.

Should this option flag be enabled by default? Of course adding also a comment that from version X.X a breaking change is present and that the old behaviour can be restored by setting `clearFingerprintAfterSuccess ` to false?

What about the inverted option flag `leaveFingerprintAfterSuccess` defaulted to false?

**Comment by Acconut** [comment]
> Should this option flag be enabled by default? Of course adding also a comment that from version X.X a breaking change is present and that the old behaviour can be restored by setting clearFingerprintAfterSuccess to false?

I would like to avoid a breaking change. Since we follow Semantic Versioning (https://semver.org/), a breaking change may only land in a new major release but we don't have the resources to maintain version 1.X and 2.Y at the same time. Furthermore, many people unfortunately don't read release notes, so such a subtle change could easily cause confusion. So I would be pleased if no default behaviour is changed.

> What about the inverted option flag leaveFingerprintAfterSuccess

If this would be enabled by default, I am also happy with this name. You can also name the flag removeFingerprintOnSuccess, similar to your branch name.

**Comment by mperrando** [comment]
Ok. Done.

I didn't like very much the almost perfectly duplicated test, so I did some refactor introducing a new context level dedicated to the urls storing.

**Comment by Acconut** [comment]
Thank you very much, this has landed in https://github.com/tus/tus-js-client/commit/926977d69067f6993699485e03884e0be88cc378. I only added a few changes for the documentation and comments

**Pull request closed without merging**
