### PR TITLE
basic nodejs support

### PR DESCRIPTION
**Pull request by export-mike**
I've been trying out the demo and it breaks when trying todo a retry.

I've updated the storage file and the fingerprint files, fingerprint is now different per environment.

storage now uses fs.writeFileSync for basic usage. This seems to me works well in a CLI setting to upload files to a tus server.

the fingerprint uses md5 hashes for node.js

### CODE REVIEW

**Comment by export-mike** [comment]
image
starting and stopping the upload continues

**Comment by Acconut** [comment]
Thank you for working on this, I wasn't available the last days so I didn't have a change to look into this. As you correctly noticed (and is also mentioned in the README: https://github.com/tus/tus-js-client#node-compatibility), the Node environment does not support resumability across a process start out of the box (for the sake of clarification, I is able to resume an interrupted upload).

In fact, @ifedapoolarewaju has also started working on resolving this limitation in #73 but since it's not our highest priority, development on this features has been stalled. May I ask how important this functionality is for you?

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)

**Comment by export-mike** [comment]
Its pretty important I'm writing a CLI with upload functionality on a shitty network. 

I literally implemented the stubbed functions for node to write to temp files on the FS.

**Comment by Acconut** [comment]
Sorry for not getting back to you sooner. There are a few  problems with your PR, which prevent me from merging this:

- it uses synchronous file operations (e.g. https://github.com/tus/tus-js-client/pull/80/files#diff-e4089b78af5860d434a175f21a2e171aR11) which are blocking the event loop and decrease performance and make the system unresponsive
- it does not have proper error handling: https://github.com/tus/tus-js-client/pull/80/files#diff-e4089b78af5860d434a175f21a2e171aR13 (logging is not the best solution :)
- it does not make the file storage configurable

@ifedapoolarewaju has also announced that he will continue working on https://github.com/tus/tus-js-client/pull/73. However, I am not sure about the time plan there.

**Pull request closed without merging**
